# =====================================
#  ██████╗ ██╗██╗  ██╗ █████╗ ██╗     
#  ██╔══██╗██║╚██╗██╔╝██╔══██╗██║     
#  ██████╔╝██║ ╚███╔╝ ███████║██║     
#  ██╔═══╝ ██║ ██╔██╗ ██╔══██║██║     
#  ██║     ██║██╔╝ ██╗██║  ██║███████╗
#  ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
#   PIXAL – PIXel-based Anomaly Locator
# =====================================

#
##
###
#### 
#### 
#### ----> Pathes <---- ####
autoencoder_model_path: &ae_path "./models/"
figure_directory: &figs_dir "./figs/"

param_path: 
  path: *ae_path 
  file: params.json

model_path:
  path: *ae_path
  model_name: "testModel"

fig_path:
  path: *figs_dir


###
##
#
##
###
########## ----> Preprocessing <---- ###########
preprocessing:
  max_workers: 8

########### ----> Memory Handling, Inputs and Hyperparameters<----####

#### ----> Memory <---- ####
enable_memory_growth: False
TF_GPU_ALLOCATOR: False
mixed_precision: False

#### ----> CPU <---- ####
Available_CPU: 24
CPU_MULTI_THREADING: False
HYBRID_MODE: False  # utilize both CPU and GPU

#### ----> Model <---- ####
Model_name: "testModel"  #incase input model is different than data name
seed: 101

#### ----> Architecture <---- ####

autoencoder_architecture: [800,400,200,100,50] # Last index is latent layer. Gets mirrored in code
label_latent_size: 50 # Size of the latent layer for the label. This gets added to the latent layer of the autoencoder

#### ----> Training <---- ####
use_gradient_tape: False # Gradient tape is used for full control of training cycle. Such as custom loss functions, custom optimization, etc. (reinforcement learning, adversarial learning)

###----> NN Hyperparameters <----###
n_epochs: 1000
batchsize: 16

learning_rate: 1e-5
l2_regularization: 0.01 #smaller values: ex. 1e-4 Apply lighter regularization, allowing weights to grow larger without as much penalty.
loss_function: "mse"
metric_accuracy: "SparseCategoricalAccuracy" #CategoricalAccuracy <--- May need this when implementing image sets

##----> STOP LOSS <----##
patience: 30
min_delta: 3

#
##
###
####
##### ----> PLOTTING <----#####

scatter_comparison: ['forward', 'data'] #,'backward']  # this plots backward passing, forward passing, and data on same plot. Remove any if once cares to do so

plot_modulus: 10  # makes number of plots w.r.t. modulus of latent size

guassian_fig_size: 10  # x and y bounds of gaussian figure

## Used for testing ideal z-space (gaussian distribution), with fake signal (no idea if anomalies would be found here)
use_test_gaussian: True
inject_signal: False


