# *************** BASE PATH. DO NOT CHANGE ***************
out_path: &out_path "./out/"
validate_out_path: &validate_out_path "./validate"


# ************** Path for component outputs **************
component_model_path: &component_model_path 
  component: "R0_Triplet_Data_Flex_F1_pink"
  base: *out_path

component_validate_path: &component_validate_path
  component: "R0_Triplet_Data_Flex_F1"
  base: *validate_out_path

# ********** DO NOT CHANGE THE FOLLOWING PATHS *********** 

model_path: &model_path
  model: "models"
  base: *component_model_path

log_path: &log_path
  log: "logs"
  base: *component_model_path

validate_log_path: &detect_log_path
  log: "logs"
  base: *component_validate_path

preprocessed_images_path: &preprocessed_images_path
  preprocessed_images: "preprocessed_images"
  base: *component_model_path

validate_preprocessed_images_path: &validate_preprocessed_images_path
  preprocessed_images: "preprocessed_images"
  base: *component_validate_path

remove_background_path: &remove_background_path
  background_removed: "background_removed"
  base: *preprocessed_images_path

validate_remove_background_path: &validate_remove_background_path
  background_removed: "background_removed"
  base: *validate_preprocessed_images_path

aligned_images_path: &aligned_images_path
  aligned_images: "aligned_images"
  base: *preprocessed_images_path

validate_aligned_images_path: &validate_aligned_images_path
  aligned_images: "aligned_images"
  base: *validate_preprocessed_images_path

fig_path: &fig_path
  fig: "figures"
  base: *component_model_path

validate_fig_path: &validate_fig_path
  fig: "figures"
  base: *component_validate_path

aligned_metrics_path: &aligned_metrics_path
  metrics: "aligned_metrics"
  base: *fig_path

validate_aligned_metrics_path: &validate_aligned_metrics_path
  metrics: "aligned_metrics"
  base: *validate_fig_path

metadata_path: &metadata_path
  metadata: "metadata"
  base: *component_model_path